### ISSUE TITLE
Issue tracker migration

### ISSUE THREAD

**Issue by mshabunin** [Itseez/opencv#4227]
We are going to migrate issue tracker from http://code.opencv.org/projects/opencv/issues to GitHub (https://github.com/Itseez/opencv/issues). Transfer is scheduled on __2015 July 27__ (next monday) (8:00 - 15:00 UTC). Process status will be reported here.

__ATTENTION!__
Large amount of notifications made during the transfer can become a problem: ~800 mail messages will be sent to each subscriber. We recommend you to temporarily unsubscribe from OpenCV repository on the transfer period (go to repository page, push "Unwatch" button and select "Not watching"). You can also use mail filter to find and remove unwanted messages, for example GMail search query is `from:(OpenCV Pushbot) Transferred from`.

Sample transfer results can be found in test repositories: 
- main -> https://github.com/mshabunin/test2/issues
- contrib -> https://github.com/mshabunin/test3/issues

Please, post any questions and suggestions here.

**Comment by mshabunin** [comment]
Fixed mistype: `June` -> `July`

**Comment by PhilLab** [comment]
Would it be possible to link the migrated issued to Github accounts so that one easily finds their migrated tickets on Github?

**Comment by mshabunin** [comment]
@PhilLab , If you mean "create issues from the name of each user" - no, it is not possible. Other way is to mention each user who took part in issue discussion, but for this we need username mapping, and generating such mapping is not obvious task. Also, second method will create a lot of additional GitHub notifications, which can not be avoided.

I'd recommend to use issue search function on GitHub and subscribe to each issue mathching your name. I will try to make python script simplifying this work for each user if necessary.

**Comment by PhilLab** [comment]
@mshabunin ok, then making a clean cut is the best solution.

**Comment by mshabunin** [comment]
- [x] Transfer process completed
- [x] [Old Issue tracker](http://code.opencv.org) turned to read-only mode
- [x] Several links from wiki and opencv.org fixed

**Comment by StevenPuttemans** [comment]
Thank you for the migration! Lets adapt our usuals and have a look on how this works!
